server {
    listen       80;
    server_name  localhost;

    charset utf-8;

    location / {
        root   /usr/share/nginx/html;
        index  成长地图.html;
    }

    location ~ \.html$ {
        root   /usr/share/nginx/html;
    }
}
